//! Integration tests for `TypedBuilder` support on generated parameter structs.
//!
//! These tests exercise the builder pattern with `#[derive(TypedBuilder)]`
//! on structs generated by `include_template!`.

// ── include_template! with builder ────────────────────────────────────

md_tmpl_macros::include_template!("prompts/greeting.tmpl.md");

// ── String fields: setter(into) ────────────────────────────────────

#[test]
fn builder_string_fields_accept_str_slices() {
    let params = greeting::Params::builder().name("Alice").count(42).build();

    assert_eq!(params.name, "Alice");
    assert_eq!(params.count, 42);
}

#[test]
fn builder_string_fields_accept_owned_strings() {
    let params = greeting::Params::builder()
        .name(String::from("Bob"))
        .count(1)
        .build();

    assert_eq!(params.name, "Bob");
}

// ── Vec fields: default ────────────────────────────────────────────

#[test]
fn builder_vec_fields_default_to_empty() {
    let params = greeting::Params::builder().name("Charlie").count(7).build();

    assert!(
        params.items.is_empty(),
        "Vec fields should default to empty"
    );
}

#[test]
fn builder_vec_fields_accept_explicit_values() {
    let params = greeting::Params::builder()
        .name("Dana")
        .count(3)
        .items(vec![
            greeting::ParamsItemsItem::builder().label("task1").build(),
            greeting::ParamsItemsItem::builder().label("task2").build(),
        ])
        .build();

    assert_eq!(params.items.len(), 2);
    assert_eq!(params.items[0].label, "task1");
    assert_eq!(params.items[1].label, "task2");
}

// ── Sub-struct builder ─────────────────────────────────────────────

#[test]
fn sub_struct_builder_works() {
    let item = greeting::ParamsItemsItem::builder().label("hello").build();

    assert_eq!(item.label, "hello");
}

// ── Full render with builder ───────────────────────────────────────

#[test]
fn builder_params_render_correctly() {
    let params = greeting::Params::builder()
        .name("World")
        .count(99)
        .items(vec![
            greeting::ParamsItemsItem::builder().label("a").build(),
        ])
        .build();

    // Module context: zero-arg render().
    let output = params.render().unwrap();
    assert_eq!(output, "\nHello World! Count: 99. Items: a");
}

// ── Code review template with builder ──────────────────────────────

md_tmpl_macros::include_template!("prompts/code_review.tmpl.md");

#[test]
fn builder_code_review_string_and_list_fields() {
    let params = code_review::Params::builder()
        .file_path("src/main.rs")
        .severity("high")
        .findings(vec![
            code_review::ParamsFindingsItem::builder()
                .line(42)
                .message("unused variable")
                .build(),
        ])
        .build();

    assert_eq!(params.file_path, "src/main.rs");
    assert_eq!(params.severity, "high");
    assert_eq!(params.findings.len(), 1);
    assert_eq!(params.findings[0].line, 42);
    assert_eq!(params.findings[0].message, "unused variable");
}

#[test]
fn builder_code_review_renders() {
    let output = code_review::Params::builder()
        .file_path("lib.rs")
        .severity("medium")
        .build()
        .render()
        .unwrap();

    assert_eq!(
        output,
        "\n# Code Review: lib.rs\n\nSeverity: medium\n\n## Findings\n"
    );
}
