// Code generated by pt-gen-go; DO NOT EDIT.

package golden

import (
	"github.com/domenukk/md-tmpl/go/md_tmpl"
)

// FindingsItem is a nested type for structured fields.
type FindingsItem struct {
	Line    int64  `json:"line"`
	Message string `json:"message"`
}

// CodeReviewParams holds the typed parameters for template rendering.
type CodeReviewParams struct {
	// FilePath parameter.
	FilePath string `json:"file_path"`
	// Severity parameter.
	Severity string `json:"severity"`
	// Findings parameter.
	Findings []FindingsItem `json:"findings"`
}

// Render renders the template with these typed parameters.
//
// Scalar fields use direct FFI setters (no reflection or serialization).
// Complex fields (list, struct, enum) are set via FlexBuffers encoding.
func (p CodeReviewParams) Render(tmpl *md_tmpl.Template) (string, error) {
	ctx := md_tmpl.NewContext()
	defer ctx.Close()
	if err := ctx.SetStr("file_path", string(p.FilePath)); err != nil {
		return "", err
	}
	if err := ctx.SetStr("severity", string(p.Severity)); err != nil {
		return "", err
	}
	if err := ctx.Set("findings", p.Findings); err != nil {
		return "", err
	}
	return tmpl.Render(ctx)
}
