// Code generated by pt-gen-go; DO NOT EDIT.

package golden

import (
	"github.com/domenukk/md-tmpl/go/md_tmpl"
)

// ItemsItem is a nested type for structured fields.
type ItemsItem struct {
	Label string `json:"label"`
}

// GreetingParams holds the typed parameters for template rendering.
type GreetingParams struct {
	// Name parameter.
	Name string `json:"name"`
	// Count parameter.
	Count int64 `json:"count"`
	// Items parameter.
	Items []ItemsItem `json:"items"`
}

// Render renders the template with these typed parameters.
//
// Scalar fields use direct FFI setters (no reflection or serialization).
// Complex fields (list, struct, enum) are set via FlexBuffers encoding.
func (p GreetingParams) Render(tmpl *md_tmpl.Template) (string, error) {
	ctx := md_tmpl.NewContext()
	defer ctx.Close()
	if err := ctx.SetStr("name", string(p.Name)); err != nil {
		return "", err
	}
	if err := ctx.SetInt("count", int64(p.Count)); err != nil {
		return "", err
	}
	if err := ctx.Set("items", p.Items); err != nil {
		return "", err
	}
	return tmpl.Render(ctx)
}
