// Auto-generated by md-tmpl codegen
// Do not edit manually.

/** Nested type for `FindingsItem`. */
export interface FindingsItem {
  readonly line: number;
  readonly message: string;
}

/** Template parameters. */
export interface Params {
  /** Type: `str` */
  readonly file_path: string;
  /** Type: `str` */
  readonly severity: string;
  /** Type: `list(…)` */
  readonly findings: readonly FindingsItem[];
}

/**
 * Render a template with type-checked parameters.
 *
 * @example
 * ```ts
 * import { Template } from "md-tmpl";
 * const tmpl = Template.fromFile("my_template.tmpl.md");
 * const output = render(tmpl, { file_path: ... });
 * ```
 */
export function render(tmpl: import("md-tmpl").Template, params: Params): string {
  return tmpl.render(params as Record<string, unknown>);
}
