// Auto-generated by md-tmpl codegen
// Do not edit manually.

/** Nested type for `ItemsItem`. */
export interface ItemsItem {
  readonly label: string;
}

/** Template parameters. */
export interface Params {
  /** Type: `str` */
  readonly name: string;
  /** Type: `int` */
  readonly count: number;
  /** Type: `list(…)` */
  readonly items: readonly ItemsItem[];
}

/**
 * Render a template with type-checked parameters.
 *
 * @example
 * ```ts
 * import { Template } from "md-tmpl";
 * const tmpl = Template.fromFile("my_template.tmpl.md");
 * const output = render(tmpl, { name: ... });
 * ```
 */
export function render(tmpl: import("md-tmpl").Template, params: Params): string {
  return tmpl.render(params as Record<string, unknown>);
}
