// Auto-generated by md-tmpl codegen
// Do not edit manually.

/** Discriminant tag names of `Priority`. */
export type PriorityKind = "Critical" | "High" | "Medium" | "Low";

/** Enum type: Critical | High | Medium | Low. */
export type Priority = "Critical" | "High" | "Medium" | "Low";

/** Companion namespace for `Priority`: variant constructors + helpers. */
export const Priority = {
  Critical: "Critical" as const,
  High: "High" as const,
  Medium: "Medium" as const,
  Low: "Low" as const,
  kinds: ["Critical", "High", "Medium", "Low"] as const,
  kindOf: (v: Priority): PriorityKind => v,
  is: (v: Priority, k: PriorityKind): boolean => v === k,
  match: <R>(v: Priority, arms: { Critical: (v: "Critical") => R; High: (v: "High") => R; Medium: (v: "Medium") => R; Low: (v: "Low") => R }): R => {
    switch (v) {
      case "Critical": return arms["Critical"](v);
      case "High": return arms["High"](v);
      case "Medium": return arms["Medium"](v);
      case "Low": return arms["Low"](v);
    }
    throw new Error(`unhandled Priority variant: ${JSON.stringify(v)}`);
  },
} as const;

/** Nested type for `TasksItem`. */
export interface TasksItem {
  readonly name: string;
  readonly urgency: Priority;
}

/** Template parameters. */
export interface Params {
  /** Type: `str` */
  readonly title: string;
  /** Type: `Priority` */
  readonly priority: Priority;
  /** Type: `list(…)` */
  readonly tasks: readonly TasksItem[];
}

/**
 * Render a template with type-checked parameters.
 *
 * @example
 * ```ts
 * import { Template } from "md-tmpl";
 * const tmpl = Template.fromFile("my_template.tmpl.md");
 * const output = render(tmpl, { title: ... });
 * ```
 */
export function render(tmpl: import("md-tmpl").Template, params: Params): string {
  return tmpl.render(params as Record<string, unknown>);
}
