"""Type stubs for the prompt_templates package.

Provides type information for the native Rust extension module and
pure-Python helpers. These stubs enable IDE autocompletion and type
checking via mypy/pyright when the ``py.typed`` marker is present.
"""

from typing import Any

class Template:
    """A parsed, validated template ready for rendering."""

    @staticmethod
    def from_file(path: str) -> "Template": ...
    @staticmethod
    def from_source(source: str) -> "Template": ...
    @staticmethod
    def from_source_allowing_unused(source: str) -> "Template": ...
    @staticmethod
    def from_source_with_base_dir(source: str, base_dir: str) -> "Template": ...
    def render(self, *, allow_extra: bool = False, **kwargs: Any) -> str: ...
    def render_dict(
        self, params: dict[str, Any], *, allow_extra: bool = False
    ) -> str: ...
    def declarations(self) -> list[tuple[str, str]]: ...
    def source_hash(self) -> int: ...
    def defaults(self) -> dict[str, Any]: ...
    def consts(self) -> dict[str, Any]: ...
    def imported_consts(self) -> dict[str, Any]: ...
    def validate_declarations_against(
        self, expected: list[tuple[str, str]]
    ) -> None: ...
    def body(self) -> str: ...
    def set_max_include_depth(self, depth: int) -> None: ...
    def __repr__(self) -> str: ...

class TemplateCache:
    """Content-hashed template cache for hot-reload scenarios."""

    def __init__(self) -> None: ...
    def load(self, path: str) -> Template: ...
    def clear(self) -> None: ...
    def template_count(self) -> int: ...
    def include_count(self) -> int: ...

def template(path: str) -> Any: ...
def load_template(path: str) -> Template: ...
def load_types(path: str, *, pick: list[str] | None = None) -> Any: ...
def prompt_template_import_hook(*, search_paths: list[str] | None = None) -> None: ...
def variant(cls: type) -> type: ...

class Variants:
    """Base class for defining variant enums."""

    ...
