#!/usr/bin/env python3
"""Codegen freshness checker and golden stub generator.

Verifies that static type stubs generated by TypeScript, Go, and Python
generator engines match committed golden files under tests/golden_stubs/.

Usage:
    python3 scripts/lint_codegen.py --check   # Verify zero-diff (default)
    python3 scripts/lint_codegen.py --write   # Regenerate golden files on disk
"""

import argparse
import sys
import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

TEMPLATES = [
    ("greeting", REPO_ROOT / "crates/md-tmpl/prompts/greeting.tmpl.md"),
    ("code_review", REPO_ROOT / "crates/md-tmpl/prompts/code_review.tmpl.md"),
    ("task_report", REPO_ROOT / "crates/md-tmpl/prompts/task_report.tmpl.md"),
]

GOLDEN_DIR = REPO_ROOT / "tests" / "golden_stubs"


def generate_ts(tmpl_path: Path) -> str:
    rel_path = tmpl_path.relative_to(REPO_ROOT)
    cmd = [
        "node",
        "-e",
        f'import("./crates/md-tmpl-typescript/dist/codegen.js").then(m => process.stdout.write(m.generateTypesFromFile("{rel_path}")))',
    ]
    res = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True, check=True)
    return res.stdout


def generate_go(tmpl_path: Path) -> str:
    with tempfile.NamedTemporaryFile(suffix=".go", delete=False) as tmp:
        tmp_out = Path(tmp.name)
    try:
        cmd = [
            "go",
            "run",
            ".",
            "-input",
            str(tmpl_path.resolve()),
            "-output",
            str(tmp_out.resolve()),
            "-package",
            "golden",
        ]
        subprocess.run(
            cmd,
            cwd=REPO_ROOT / "go" / "cmd" / "pt-gen-go",
            capture_output=True,
            text=True,
            check=True,
        )
        return tmp_out.read_text(encoding="utf-8")
    finally:
        if tmp_out.exists():
            tmp_out.unlink()


def generate_python(tmpl_path: Path) -> str:
    rel_path = str(tmpl_path.relative_to(REPO_ROOT))
    py_bin = REPO_ROOT / "crates/md-tmpl-python/.venv/bin/python3"
    code = (
        "import sys; "
        "from md_tmpl._md_tmpl import generate_python_source_for_template; "
        f"sys.stdout.write(generate_python_source_for_template({rel_path!r}))"
    )
    cmd = [str(py_bin), "-c", code]
    res = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True, check=True)
    return res.stdout


LANGUAGES = [
    ("ts", ".ts", generate_ts),
    ("go", ".go", generate_go),
    ("python", ".py", generate_python),
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Codegen freshness tool")
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check",
        action="store_true",
        default=True,
        help="Check that generated files match disk (default)",
    )
    group.add_argument(
        "--write",
        action="store_true",
        help="Overwrite golden files on disk with generated output",
    )
    args = parser.parse_args()
    mode_write = args.write

    failed = False
    total_checks = 0

    for lang_dir, ext, gen_fn in LANGUAGES:
        target_dir = GOLDEN_DIR / lang_dir
        if mode_write:
            target_dir.mkdir(parents=True, exist_ok=True)

        for stem, tmpl_path in TEMPLATES:
            total_checks += 1
            golden_file = target_dir / f"{stem}{ext}"
            print(f"[{lang_dir.upper()}] Processing {stem} -> {golden_file.relative_to(REPO_ROOT)}... ", end="", flush=True)

            try:
                generated = gen_fn(tmpl_path)
            except Exception as e:
                print("ERROR during generation!")
                print(f"  {e}")
                failed = True
                continue

            if mode_write:
                golden_file.write_text(generated, encoding="utf-8")
                print("WRITTEN")
            else:
                if not golden_file.exists():
                    print("MISSING on disk!")
                    failed = True
                    continue
                expected = golden_file.read_text(encoding="utf-8")
                if generated == expected:
                    print("OK (zero-diff)")
                else:
                    print("STALE / MISMATCH!")
                    print(f"--- Golden: {golden_file}")
                    print("+++ Regenerated output differs.")
                    failed = True

    if mode_write:
        print(f"\nSuccessfully generated {total_checks} golden stubs.")
        return 0
    else:
        if failed:
            print("\nCodegen freshness check FAILED! Run 'just gen-stubs' to update golden files.")
            return 1
        print(f"\nCodegen freshness check PASSED ({total_checks} stubs verified zero-diff).")
        return 0


if __name__ == "__main__":
    sys.exit(main())
