//! Integration tests for `TypedBuilder` support on generated parameter structs.
//!
//! These tests exercise the builder pattern with `#[derive(TypedBuilder)]`
//! on structs generated by `include_types!` and `template_params_struct!`.

// ── include_types! with builder ────────────────────────────────────

prompt_templates_macros::include_types!("prompts/greeting.tmpl.md");

// ── String fields: setter(into) ────────────────────────────────────

#[test]
fn builder_string_fields_accept_str_slices() {
    let params = greeting::Params::builder().name("Alice").count(42).build();

    assert_eq!(params.name, "Alice");
    assert_eq!(params.count, 42);
}

#[test]
fn builder_string_fields_accept_owned_strings() {
    let params = greeting::Params::builder()
        .name(String::from("Bob"))
        .count(1)
        .build();

    assert_eq!(params.name, "Bob");
}

// ── Vec fields: default ────────────────────────────────────────────

#[test]
fn builder_vec_fields_default_to_empty() {
    let params = greeting::Params::builder().name("Charlie").count(7).build();

    assert!(
        params.items.is_empty(),
        "Vec fields should default to empty"
    );
}

#[test]
fn builder_vec_fields_accept_explicit_values() {
    let params = greeting::Params::builder()
        .name("Dana")
        .count(3)
        .items(vec![
            greeting::ParamsItemsItem::builder().label("task1").build(),
            greeting::ParamsItemsItem::builder().label("task2").build(),
        ])
        .build();

    assert_eq!(params.items.len(), 2);
    assert_eq!(params.items[0].label, "task1");
    assert_eq!(params.items[1].label, "task2");
}

// ── Sub-struct builder ─────────────────────────────────────────────

#[test]
fn sub_struct_builder_works() {
    let item = greeting::ParamsItemsItem::builder().label("hello").build();

    assert_eq!(item.label, "hello");
}

// ── Full render with builder ───────────────────────────────────────

#[test]
fn builder_params_render_correctly() {
    let tmpl = prompt_templates_macros::include_template!("prompts/greeting.tmpl.md");

    let params = greeting::Params::builder()
        .name("World")
        .count(99)
        .items(vec![
            greeting::ParamsItemsItem::builder().label("a").build(),
        ])
        .build();

    let output = params.render(tmpl).unwrap();
    assert!(output.contains("Hello World!"), "got: {output}");
    assert!(output.contains("Count: 99"), "got: {output}");
    assert!(output.contains('a'), "got: {output}");
}

// ── template_params_struct! with builder ───────────────────────────

prompt_templates_macros::template_params_struct!("prompts/greeting.tmpl.md" => GreetingParams);

#[test]
fn template_params_struct_builder_works() {
    let params = GreetingParams::builder().name("Eve").count(0).build();

    assert_eq!(params.name, "Eve");
    assert_eq!(params.count, 0);
    assert!(params.items.is_empty());
}

#[test]
fn template_params_struct_builder_renders() {
    let tmpl = prompt_templates_macros::include_template!("prompts/greeting.tmpl.md");

    let output = GreetingParams::builder()
        .name("Frank")
        .count(5)
        .items(vec![
            GreetingParamsItemsItem::builder().label("item1").build(),
        ])
        .build()
        .render(tmpl)
        .unwrap();

    assert!(output.contains("Frank"), "got: {output}");
    assert!(output.contains("Count: 5"), "got: {output}");
    assert!(output.contains("item1"), "got: {output}");
}

// ── Code review template with multiple list fields ─────────────────

prompt_templates_macros::template_params_struct!("prompts/code_review.tmpl.md" => CodeReviewParams);

#[test]
fn builder_code_review_string_and_list_fields() {
    let params = CodeReviewParams::builder()
        .file_path("src/main.rs")
        .severity("high")
        .findings(vec![
            CodeReviewParamsFindingsItem::builder()
                .line(42)
                .message("unused variable")
                .build(),
        ])
        .build();

    assert_eq!(params.file_path, "src/main.rs");
    assert_eq!(params.severity, "high");
    assert_eq!(params.findings.len(), 1);
    assert_eq!(params.findings[0].line, 42);
    assert_eq!(params.findings[0].message, "unused variable");
}

#[test]
fn builder_code_review_renders() {
    let tmpl = prompt_templates_macros::include_template!("prompts/code_review.tmpl.md");

    let output = CodeReviewParams::builder()
        .file_path("lib.rs")
        .severity("medium")
        .build()
        .render(tmpl)
        .unwrap();

    assert!(output.contains("lib.rs"), "got: {output}");
    assert!(output.contains("medium"), "got: {output}");
}
