package prompt_templates

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

// GenOption configures code generation via the functional options pattern.
type GenOption func(*genOptions)

type genOptions struct {
	packageName  string
	paramsName   string
	renderHelper bool
}

func defaultGenOptions() *genOptions {
	return &genOptions{
		packageName:  "main",
		paramsName:   "",
		renderHelper: true,
	}
}

// WithPackageName sets the Go package name in the generated source.
// Default: "main".
func WithPackageName(name string) GenOption {
	return func(o *genOptions) { o.packageName = name }
}

// WithParamsName sets the name of the generated params struct.
// Default: derived from the file stem in PascalCase + "Params".
// When generating from source (no filename), defaults to "Params".
func WithParamsName(name string) GenOption {
	return func(o *genOptions) { o.paramsName = name }
}

// WithRenderHelper controls whether a Render helper method is generated.
// Default: true.
func WithRenderHelper(include bool) GenOption {
	return func(o *genOptions) { o.renderHelper = include }
}

// GenerateTypes generates Go source code from a template source string.
//
// The source must include YAML frontmatter with parameter declarations.
// Returns valid, gofmt-formatted Go source code as a string.
func GenerateTypes(source string, opts ...GenOption) (string, error) {
	o := defaultGenOptions()
	for _, fn := range opts {
		fn(o)
	}
	if o.paramsName == "" {
		o.paramsName = "Params"
	}

	tmpl, err := FromSourceAllowingUnused(source)
	if err != nil {
		return "", fmt.Errorf("parsing template source: %w", err)
	}
	defer tmpl.Close()

	return generateFromTemplate(tmpl, o)
}

// GenerateTypesFromFile generates Go source code from a .tmpl.md file.
//
// The params struct name defaults to PascalCase(fileStem) + "Params"
// unless overridden with [WithParamsName].
func GenerateTypesFromFile(path string, opts ...GenOption) (string, error) {
	o := defaultGenOptions()
	for _, fn := range opts {
		fn(o)
	}
	if o.paramsName == "" {
		stem := strings.TrimSuffix(filepath.Base(path), ".tmpl.md")
		if stem == filepath.Base(path) {
			stem = strings.TrimSuffix(stem, filepath.Ext(stem))
		}
		o.paramsName = toPascalCase(stem) + "Params"
	}

	source, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("reading template file: %w", err)
	}

	tmpl, err := FromSourceAllowingUnused(string(source))
	if err != nil {
		return "", fmt.Errorf("parsing template file: %w", err)
	}
	defer tmpl.Close()

	return generateFromTemplate(tmpl, o)
}

// ---------------------------------------------------------------------------
// Code generation core
// ---------------------------------------------------------------------------

// codegenContext accumulates generated Go source pieces.
type codegenContext struct {
	opts           *genOptions
	auxiliaryTypes []string        // Nested struct/enum definitions.
	generatedNames map[string]bool // Dedup set for generated type names.
}

func newCodegenContext(opts *genOptions) *codegenContext {
	return &codegenContext{
		opts:           opts,
		generatedNames: make(map[string]bool),
	}
}

func generateFromTemplate(tmpl *Template, opts *genOptions) (string, error) {
	decls := tmpl.Declarations()

	ctx := newCodegenContext(opts)

	// First pass: resolve all types (may generate auxiliary definitions).
	type fieldInfo struct {
		name     string
		goType   string
		typeKind typeKind // Retained for generating optimal setter calls.
	}
	fields := make([]fieldInfo, 0, len(decls))
	for _, d := range decls {
		parsed, err := parseTypeSpec(d.Type)
		if err != nil {
			return "", fmt.Errorf("parsing type for %q: %w", d.Name, err)
		}
		goType := ctx.resolveType(d.Name, parsed)
		fields = append(fields, fieldInfo{name: d.Name, goType: goType, typeKind: parsed.kind})
	}

	// Build the output.
	var b strings.Builder

	b.WriteString("// Code generated by pt-gen-go; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.packageName)

	// Imports — include prompt_templates for the Render helper.
	if opts.renderHelper {
		b.WriteString("import (\n")
		b.WriteString("\t\"github.com/domenukk/prompt-templates/go/prompt_templates\"\n")
		b.WriteString(")\n\n")
	}

	// Auxiliary types (enums, nested structs).
	for _, aux := range ctx.auxiliaryTypes {
		b.WriteString(aux)
		b.WriteString("\n\n")
	}

	// Main params struct.
	fmt.Fprintf(&b, "// %s holds the typed parameters for template rendering.\n", opts.paramsName)
	fmt.Fprintf(&b, "type %s struct {\n", opts.paramsName)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t// %s parameter.\n", toPascalCase(f.name))
		fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", toPascalCase(f.name), f.goType, f.name)
	}
	b.WriteString("}\n")

	// Render helper method — emit direct SetStr/SetInt/etc. calls for scalar
	// fields to bypass reflect + FlexBuffers serialization entirely.
	if opts.renderHelper {
		b.WriteString("\n")
		fmt.Fprintf(&b, "// Render renders the template with these typed parameters.\n")
		fmt.Fprintf(&b, "//\n")
		fmt.Fprintf(&b, "// Scalar fields use direct FFI setters (no reflection or serialization).\n")
		fmt.Fprintf(&b, "// Complex fields (list, struct, enum) are set via FlexBuffers encoding.\n")
		fmt.Fprintf(&b, "func (p %s) Render(tmpl *prompt_templates.Template) (string, error) {\n", opts.paramsName)
		b.WriteString("\tctx := prompt_templates.NewContext()\n")
		b.WriteString("\tdefer ctx.Close()\n")
		for _, f := range fields {
			goField := toPascalCase(f.name)
			switch f.typeKind {
			case kindStr:
				fmt.Fprintf(&b, "\tif err := ctx.SetStr(%q, string(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			case kindInt:
				fmt.Fprintf(&b, "\tif err := ctx.SetInt(%q, int64(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			case kindFloat:
				fmt.Fprintf(&b, "\tif err := ctx.SetFloat(%q, float64(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			case kindBool:
				fmt.Fprintf(&b, "\tif err := ctx.SetBool(%q, bool(p.%s)); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			default:
				// Complex types (list, struct, enum): use generic Set which
				// marshals via FlexBuffers — still a single FFI call.
				fmt.Fprintf(&b, "\tif err := ctx.Set(%q, p.%s); err != nil {\n\t\treturn \"\", err\n\t}\n", f.name, goField)
			}
		}
		b.WriteString("\treturn tmpl.Render(ctx)\n")
		b.WriteString("}\n")
	}

	// Format with gofmt.
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return b.String(), fmt.Errorf("formatting generated code: %w\n\nRaw output:\n%s", err, b.String())
	}
	return string(formatted), nil
}

// resolveType converts a parsed typeNode into a Go type string, emitting
// auxiliary type definitions as needed.
func (c *codegenContext) resolveType(fieldName string, node typeNode) string {
	switch node.kind {
	case kindStr:
		return "string"
	case kindInt:
		return "int64"
	case kindFloat:
		return "float64"
	case kindBool:
		return "bool"

	case kindList:
		if len(node.fields) == 0 {
			return "[]any"
		}
		itemName := toPascalCase(fieldName) + "Item"
		c.emitStruct(itemName, node.fields)
		return "[]" + itemName

	case kindStruct:
		if len(node.fields) == 0 {
			return "map[string]any"
		}
		structName := toPascalCase(fieldName)
		c.emitStruct(structName, node.fields)
		return structName

	case kindEnum:
		enumName := toPascalCase(fieldName)
		c.emitEnum(enumName, node.variants)
		return enumName

	case kindOption:
		if node.innerType == nil {
			return "any"
		}
		inner := c.resolveType(fieldName, *node.innerType)
		return "*" + inner

	case kindScalarList:
		if node.innerType == nil {
			return "[]any"
		}
		inner := c.resolveType(fieldName, *node.innerType)
		return "[]" + inner

	case kindAlias:
		return "any"

	default:
		return "any"
	}
}

// emitStruct generates a Go struct type for list items or struct values.
func (c *codegenContext) emitStruct(name string, fields []fieldNode) {
	if c.generatedNames[name] {
		return
	}
	c.generatedNames[name] = true

	var b strings.Builder
	fmt.Fprintf(&b, "// %s is a nested type for structured fields.\n", name)
	fmt.Fprintf(&b, "type %s struct {\n", name)
	for _, f := range fields {
		goType := c.resolveType(f.name, f.typeNode)
		fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", toPascalCase(f.name), goType, f.name)
	}
	b.WriteString("}")

	c.auxiliaryTypes = append(c.auxiliaryTypes, b.String())
}

// emitEnum generates Go type definitions for an enum.
func (c *codegenContext) emitEnum(name string, variants []variantNode) {
	if c.generatedNames[name] {
		return
	}
	c.generatedNames[name] = true

	// Check if all variants are unit (no fields).
	allUnit := true
	for _, v := range variants {
		if len(v.fields) > 0 {
			allUnit = false
			break
		}
	}

	if allUnit {
		c.emitUnitEnum(name, variants)
	} else {
		c.emitMixedEnum(name, variants)
	}
}

// emitUnitEnum generates a string-based enum with const block.
func (c *codegenContext) emitUnitEnum(name string, variants []variantNode) {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s is a string enum type.\n", name)
	fmt.Fprintf(&b, "type %s string\n\n", name)
	fmt.Fprintf(&b, "const (\n")
	for _, v := range variants {
		constName := name + v.name
		fmt.Fprintf(&b, "\t// %s is the %q variant.\n", constName, v.name)
		fmt.Fprintf(&b, "\t%s %s = %q\n", constName, name, v.name)
	}
	b.WriteString(")")

	c.auxiliaryTypes = append(c.auxiliaryTypes, b.String())
}

// emitMixedEnum generates an interface-based sum type for enums with struct variants.
func (c *codegenContext) emitMixedEnum(name string, variants []variantNode) {
	var b strings.Builder

	// Interface type.
	sealMethod := "is" + name
	fmt.Fprintf(&b, "// %s is a sum type (sealed interface).\n", name)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Possible variants:\n")
	for _, v := range variants {
		fmt.Fprintf(&b, "//   - %s%s\n", name, v.name)
	}
	fmt.Fprintf(&b, "type %s interface {\n", name)
	fmt.Fprintf(&b, "\t%s()\n", sealMethod)
	b.WriteString("}\n\n")

	// Variant types.
	for _, v := range variants {
		variantTypeName := name + v.name
		if len(v.fields) == 0 {
			// Unit variant → empty struct.
			fmt.Fprintf(&b, "// %s is the %q unit variant of %s.\n", variantTypeName, v.name, name)
			fmt.Fprintf(&b, "type %s struct{}\n\n", variantTypeName)
		} else {
			// Struct variant.
			fmt.Fprintf(&b, "// %s is the %q struct variant of %s.\n", variantTypeName, v.name, name)
			fmt.Fprintf(&b, "type %s struct {\n", variantTypeName)
			for _, f := range v.fields {
				goType := c.resolveType(f.name, f.typeNode)
				fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", toPascalCase(f.name), goType, f.name)
			}
			b.WriteString("}\n\n")
		}
		fmt.Fprintf(&b, "func (%s) %s() {}\n\n", variantTypeName, sealMethod)
	}

	// Trim trailing newlines.
	result := strings.TrimRight(b.String(), "\n")
	c.auxiliaryTypes = append(c.auxiliaryTypes, result)
}

// ---------------------------------------------------------------------------
// TypeSpec parser
// ---------------------------------------------------------------------------

// typeKind classifies a parsed type.
type typeKind int

const (
	kindStr typeKind = iota
	kindInt
	kindFloat
	kindBool
	kindList
	kindStruct
	kindEnum
	kindOption     // option(T) — nullable wrapper.
	kindScalarList // scalar_list(T) — homogeneous typed list.
	kindAlias      // Unresolved type alias — maps to any.
)

// typeNode is a parsed type specification.
type typeNode struct {
	kind      typeKind
	fields    []fieldNode   // For list and struct.
	variants  []variantNode // For enum.
	innerType *typeNode     // For option and scalar_list.
}

// fieldNode is a name-type pair inside a list/struct/variant.
type fieldNode struct {
	name     string
	typeNode typeNode
}

// variantNode is one variant of an enum.
type variantNode struct {
	name   string
	fields []fieldNode // Empty for unit variants.
}

// parseTypeSpec parses a TypeSpec string like "str", "list(x = str, y = int)",
// "enum(A, B(x = str))", etc.
func parseTypeSpec(spec string) (typeNode, error) {
	spec = strings.TrimSpace(spec)
	p := &typeParser{input: spec}
	node, err := p.parseType()
	if err != nil {
		return typeNode{}, err
	}
	return node, nil
}

// typeParser is a simple recursive-descent parser for TypeSpec strings.
type typeParser struct {
	input string
	pos   int
}

func (p *typeParser) parseType() (typeNode, error) {
	p.skipWhitespace()
	ident := p.readIdent()
	if ident == "" {
		return typeNode{}, fmt.Errorf("expected type identifier at position %d in %q", p.pos, p.input)
	}

	switch ident {
	case "str":
		return typeNode{kind: kindStr}, nil
	case "int":
		return typeNode{kind: kindInt}, nil
	case "float":
		return typeNode{kind: kindFloat}, nil
	case "bool":
		return typeNode{kind: kindBool}, nil
	case "list":
		return p.parseCompound(kindList)
	case "struct":
		return p.parseCompound(kindStruct)
	case "enum":
		return p.parseEnum()
	case "option":
		return p.parseWrapped(kindOption)
	case "scalar_list":
		return p.parseWrapped(kindScalarList)
	default:
		// Type alias or unknown type — use any. The engine resolves
		// aliases at runtime; codegen cannot expand them without the
		// full type alias map.
		return typeNode{kind: kindAlias}, nil
	}
}

// parseWrapped handles option(T) and scalar_list(T) — types wrapping a single inner type.
func (p *typeParser) parseWrapped(kind typeKind) (typeNode, error) {
	p.skipWhitespace()
	if !p.consume('(') {
		return typeNode{}, fmt.Errorf("expected '(' after type keyword at position %d in %q", p.pos, p.input)
	}
	p.skipWhitespace()

	inner, err := p.parseType()
	if err != nil {
		return typeNode{}, fmt.Errorf("parsing inner type: %w", err)
	}

	p.skipWhitespace()
	if !p.consume(')') {
		return typeNode{}, fmt.Errorf("expected ')' at position %d in %q", p.pos, p.input)
	}

	return typeNode{kind: kind, innerType: &inner}, nil
}

func (p *typeParser) parseCompound(kind typeKind) (typeNode, error) {
	p.skipWhitespace()
	if !p.consume('(') {
		// Bare list/struct without fields.
		return typeNode{kind: kind}, nil
	}

	// For list types, check if this is a scalar list (e.g., list(str))
	// by peeking ahead: if the first token is a type keyword not followed
	// by '=', it's a scalar list.
	if kind == kindList {
		saved := p.pos
		p.skipWhitespace()
		ident := p.readIdent()
		p.skipWhitespace()
		if ident != "" && p.peek() == ')' {
			// It's a scalar list like list(str).
			p.pos++ // consume ')'
			innerNode, err := parseTypeSpec(ident)
			if err != nil {
				return typeNode{}, fmt.Errorf("parsing scalar list element type: %w", err)
			}
			return typeNode{kind: kindScalarList, innerType: &innerNode}, nil
		}
		// Not a scalar list — restore position and parse as normal fields.
		p.pos = saved
	}

	fields, err := p.parseFields(')')
	if err != nil {
		return typeNode{}, err
	}

	return typeNode{kind: kind, fields: fields}, nil
}

func (p *typeParser) parseFields(closer rune) ([]fieldNode, error) {
	var fields []fieldNode
	for {
		p.skipWhitespace()
		if p.peek() == byte(closer) {
			p.pos++
			break
		}
		if len(fields) > 0 {
			if !p.consume(',') {
				return nil, fmt.Errorf("expected ',' or '%c' at position %d in %q", closer, p.pos, p.input)
			}
			p.skipWhitespace()
		}

		name := p.readIdent()
		if name == "" {
			return nil, fmt.Errorf("expected field name at position %d in %q", p.pos, p.input)
		}
		p.skipWhitespace()
		if !p.consume('=') {
			return nil, fmt.Errorf("expected '=' after field name %q at position %d in %q", name, p.pos, p.input)
		}
		p.skipWhitespace()

		fieldType, err := p.parseType()
		if err != nil {
			return nil, fmt.Errorf("parsing type for field %q: %w", name, err)
		}
		fields = append(fields, fieldNode{name: name, typeNode: fieldType})
	}
	return fields, nil
}

func (p *typeParser) parseEnum() (typeNode, error) {
	p.skipWhitespace()
	if !p.consume('(') {
		return typeNode{}, fmt.Errorf("expected '(' after 'enum' at position %d in %q", p.pos, p.input)
	}

	var variants []variantNode
	for {
		p.skipWhitespace()
		if p.peek() == ')' {
			p.pos++
			break
		}
		if len(variants) > 0 {
			if !p.consume(',') {
				return typeNode{}, fmt.Errorf("expected ',' or ')' at position %d in %q", p.pos, p.input)
			}
			p.skipWhitespace()
		}

		name := p.readIdent()
		if name == "" {
			return typeNode{}, fmt.Errorf("expected variant name at position %d in %q", p.pos, p.input)
		}

		p.skipWhitespace()
		var fields []fieldNode
		if p.peek() == '(' {
			p.pos++ // consume '('
			var err error
			fields, err = p.parseFields(')')
			if err != nil {
				return typeNode{}, fmt.Errorf("parsing variant %q fields: %w", name, err)
			}
		}

		variants = append(variants, variantNode{name: name, fields: fields})
	}

	return typeNode{kind: kindEnum, variants: variants}, nil
}

func (p *typeParser) skipWhitespace() {
	for p.pos < len(p.input) && (p.input[p.pos] == ' ' || p.input[p.pos] == '\t' || p.input[p.pos] == '\n' || p.input[p.pos] == '\r') {
		p.pos++
	}
}

func (p *typeParser) readIdent() string {
	start := p.pos
	for p.pos < len(p.input) {
		ch := p.input[p.pos]
		if ch == '_' || (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9' && p.pos > start) {
			p.pos++
		} else {
			break
		}
	}
	return p.input[start:p.pos]
}

func (p *typeParser) peek() byte {
	if p.pos >= len(p.input) {
		return 0
	}
	return p.input[p.pos]
}

func (p *typeParser) consume(ch byte) bool {
	p.skipWhitespace()
	if p.pos < len(p.input) && p.input[p.pos] == ch {
		p.pos++
		return true
	}
	return false
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// toPascalCase converts snake_case or kebab-case to PascalCase.
func toPascalCase(s string) string {
	var result strings.Builder
	capitalizeNext := true
	for _, r := range s {
		if r == '_' || r == '-' || r == ' ' {
			capitalizeNext = true
			continue
		}
		if capitalizeNext {
			result.WriteRune(unicode.ToUpper(r))
			capitalizeNext = false
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}
