"""Type stubs for the native Rust extension module `md_tmpl._md_tmpl`."""

import os
from typing import Any

from md_tmpl._exceptions import (
    ExtraParamsError as ExtraParamsError,
    MissingParamsError as MissingParamsError,
    TemplateError as TemplateError,
    TemplatePanicError as TemplatePanicError,
    TemplateSyntaxError as TemplateSyntaxError,
    TypeMismatchError as TypeMismatchError,
)

class Template:
    @staticmethod
    def from_file(path: str | os.PathLike[str]) -> "Template": ...
    @staticmethod
    def from_source(source: str) -> "Template": ...
    @staticmethod
    def from_source_allowing_unused(source: str) -> "Template": ...
    @staticmethod
    def from_source_with_base_dir(
        source: str, base_dir: str | os.PathLike[str]
    ) -> "Template": ...
    def render(self, *, allow_extra: bool = False, **kwargs: Any) -> str: ...
    def render_dict(
        self, params: dict[str, Any], *, allow_extra: bool = False
    ) -> str: ...
    def render_cached(
        self, cache: "TemplateCache", *, allow_extra: bool = False, **kwargs: Any
    ) -> str: ...
    def render_cached_dict(
        self,
        params: dict[str, Any],
        cache: "TemplateCache",
        *,
        allow_extra: bool = False,
    ) -> str: ...
    def render_flexbuffers(
        self, buffer: bytes, *, allow_extra: bool = False
    ) -> str: ...
    def render_cached_flexbuffers(
        self,
        buffer: bytes,
        cache: "TemplateCache",
        *,
        allow_extra: bool = False,
    ) -> str: ...
    def render_json(self, json_str: str, *, allow_extra: bool = False) -> str: ...
    def render_json_cached(
        self,
        json_str: str,
        cache: "TemplateCache",
        *,
        allow_extra: bool = False,
    ) -> str: ...
    def render_empty(self) -> str: ...
    def declarations(self) -> list[tuple[str, str]]: ...
    def source_hash(self) -> int: ...
    def defaults(self) -> dict[str, Any]: ...
    def consts(self) -> dict[str, Any]: ...
    def imported_consts(self) -> dict[str, Any]: ...
    def validate_declarations_against(
        self, expected: list[tuple[str, str]]
    ) -> None: ...
    def body(self) -> str: ...
    def set_max_include_depth(self, depth: int) -> None: ...
    def __enter__(self) -> "Template": ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...
    def __repr__(self) -> str: ...

class TemplateCache:
    def __init__(self, *, max_entries: int | None = None) -> None: ...
    def load(self, path: str | os.PathLike[str]) -> Template: ...
    def clear(self) -> None: ...
    def template_count(self) -> int: ...
    def include_count(self) -> int: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> "TemplateCache": ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool: ...

def generate_types_for_template(path: str | os.PathLike[str]) -> dict[str, Any]: ...
def generate_python_source_for_template(path: str | os.PathLike[str]) -> str: ...
