"""Type stubs for the native Rust extension module `md_tmpl._md_tmpl`."""

import os
from typing import Any

from md_tmpl._exceptions import (
    ExtraParamsError as ExtraParamsError,
    MissingParamsError as MissingParamsError,
    TemplateError as TemplateError,
    TemplatePanicError as TemplatePanicError,
    TemplateSyntaxError as TemplateSyntaxError,
    TypeMismatchError as TypeMismatchError,
)

class Template:
    @staticmethod
    def from_file(path: str | os.PathLike[str]) -> "Template": ...
    @staticmethod
    def from_source(source: str) -> "Template": ...
    @staticmethod
    def from_source_allowing_unused(source: str) -> "Template": ...
    @staticmethod
    def from_source_with_base_dir(
        source: str, base_dir: str | os.PathLike[str]
    ) -> "Template": ...
    @staticmethod
    def from_source_with_env(source: str, env: dict[str, Any]) -> "Template": ...
    @staticmethod
    def from_source_with_options(
        source: str,
        *,
        base_dir: str | os.PathLike[str] | None = None,
        env: dict[str, Any] | None = None,
        allow_unused: bool = False,
    ) -> "Template": ...
    def render(self, *, allow_extra: bool = False, **kwargs: Any) -> str: ...
    def render_dict(
        self, params: dict[str, Any], *, allow_extra: bool = False
    ) -> str: ...
    def render_unchecked(self, **kwargs: Any) -> str: ...
    def render_dict_unchecked(self, params: dict[str, Any]) -> str: ...
    def render_cached(
        self, cache: "TemplateCache", *, allow_extra: bool = False, **kwargs: Any
    ) -> str: ...
    def render_cached_dict(
        self,
        params: dict[str, Any],
        cache: "TemplateCache",
        *,
        allow_extra: bool = False,
    ) -> str: ...
    def render_flexbuffers(
        self, buffer: bytes, *, allow_extra: bool = False
    ) -> str: ...
    def render_cached_flexbuffers(
        self,
        buffer: bytes,
        cache: "TemplateCache",
        *,
        allow_extra: bool = False,
    ) -> str: ...
    def render_json(self, json_str: str, *, allow_extra: bool = False) -> str: ...
    def render_cached_json(
        self,
        json_str: str,
        cache: "TemplateCache",
        *,
        allow_extra: bool = False,
    ) -> str: ...
    def render_empty(self) -> str: ...
    def declarations(self) -> list[tuple[str, str]]: ...
    def source_hash(self) -> int: ...
    def defaults(self) -> dict[str, Any]: ...
    def consts(self) -> dict[str, Any]: ...
    def imported_consts(self) -> dict[str, Any]: ...
    def validate_declarations_against(
        self, expected: list[tuple[str, str]]
    ) -> None: ...
    def body(self) -> str: ...
    def name(self) -> str | None: ...
    def description(self) -> str | None: ...
    def set_max_include_depth(self, depth: int) -> None: ...
    def __enter__(self) -> "Template":
        """Return ``self`` unchanged (intentional no-op).

        A ``Template`` holds no OS resources, so entering the context
        manager acquires nothing. Provided so ``Template`` works with
        ``with``.
        """
        ...

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool:
        """Release nothing and never suppress exceptions (intentional no-op)."""
        ...

    def __repr__(self) -> str: ...

class TemplateCache:
    def __init__(self, *, max_entries: int | None = None) -> None: ...
    def load(self, path: str | os.PathLike[str]) -> Template: ...
    def clear(self) -> None: ...
    def template_count(self) -> int: ...
    def include_count(self) -> int: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> "TemplateCache":
        """Return ``self`` unchanged (intentional no-op).

        A ``TemplateCache`` holds no OS resources, so entering the context
        manager acquires nothing. Provided so ``TemplateCache`` works with
        ``with``. Call ``clear()`` explicitly to drop cached entries.
        """
        ...

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: Any,
    ) -> bool:
        """Release nothing and never suppress exceptions (intentional no-op)."""
        ...

def generate_types_for_template(path: str | os.PathLike[str]) -> dict[str, Any]: ...
def generate_python_source_for_template(path: str | os.PathLike[str]) -> str: ...

DEFAULT_QUARANTINE_TAG: str
DEFAULT_SANITIZE_TAG: str
DEFAULT_SANITIZE_NOTICE: str
TOKEN_DELIMITERS: list[tuple[str, str]]
ROLE_TOKEN_DELIMITERS: list[tuple[str, str]]

def escape_xml(s: str) -> str: ...
def escape_json(s: str) -> str: ...
def has_control_tokens(s: str) -> bool: ...
def has_role_control_tokens(s: str) -> bool: ...
def sanitize_tokens(s: str) -> str: ...
def sanitize_role_tokens(s: str) -> str: ...
def fence(s: str, lang: str | None = None) -> str: ...
def has_quarantine_tag_breakout(
    s: str, tag_spec: str = DEFAULT_QUARANTINE_TAG
) -> bool: ...
def has_untrusted_breakout(s: str, tag_spec: str = DEFAULT_QUARANTINE_TAG) -> bool: ...
def sanitize_quarantine_payload(
    s: str, tag_spec: str = DEFAULT_QUARANTINE_TAG
) -> str: ...
def sanitize_untrusted(s: str, tag_spec: str = DEFAULT_QUARANTINE_TAG) -> str: ...
def quarantine(s: str, tag_spec: str | None = None) -> str: ...
def quarantine_untrusted(s: str, tag_spec: str | None = None) -> str: ...
def is_quarantined(s: str, tag_spec: str | None = None) -> bool: ...
def sanitize(s: str, tag_spec: str | None = None) -> str: ...
def sanitize_block(
    s: str, tag_spec: str | None = None, custom_notice: str | None = None
) -> str: ...
def is_sanitized_block(
    s: str, tag_spec: str | None = None, custom_notice: str | None = None
) -> bool: ...
def unsanitize_block(
    s: str, tag_spec: str | None = None, custom_notice: str | None = None
) -> str | None: ...
